name: Nuke ops (lite)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to fix (e.g. main or dev-ui)"
        required: true
        default: "main"

permissions:
  contents: write

jobs:
  nuke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo without submodules
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0
          submodules: false  # 关键：不触发子模块

      - name: Remove gitlink and .gitmodules, then push
        run: |
          set -eux
          # 清理索引里的 gitlink 与工作区
          git rm -r --cached ops || true
          rm -rf ops || true
          [ -f .gitmodules ] && rm -f .gitmodules || true

          git add -A
          if git diff --cached --quiet; then
            echo "Nothing to remove"; exit 0
          fi

          git config user.name  "actions-user"
          git config user.email "actions@users.noreply.github.com"

          git commit -m "chore: remove broken 'ops' submodule pointer"
          git push
