name: Nuke broken ops

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to fix (e.g. dev-ui or main)"
        required: true
        default: "dev-ui"

permissions:
  contents: write

jobs:
  nuke:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo WITHOUT submodules
        run: |
          set -eux
          git clone --no-recurse-submodules "https://github.com/${GITHUB_REPOSITORY}.git" repo
          cd repo
          git checkout "${{ github.event.inputs.branch }}"
          git config user.name  "actions-user"
          git config user.email "actions@users.noreply.github.com"

          # 硬删残留 submodule 指针与目录
          git rm -r --cached ops || true
          rm -rf ops || true
          if [ -f .gitmodules ]; then rm -f .gitmodules || true; fi

          # 提交并推送（如果确有变更）
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: remove broken 'ops' submodule pointer"
            git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
            git push origin "${{ github.event.inputs.branch }}"
          else
            echo "Nothing to remove."
          fi
