name: Nuke broken ops (with PR fallback)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to fix (e.g. dev-ui or main)"
        required: true
        default: "main"

permissions:
  contents: write
  pull-requests: write

jobs:
  nuke:
    runs-on: ubuntu-latest
    steps:
      - name: Clone WITHOUT submodules
        run: |
          set -eux
          git clone --no-recurse-submodules "https://github.com/${GITHUB_REPOSITORY}.git" repo
          cd repo
          git checkout "${{ github.event.inputs.branch }}"

          git config user.name  "actions-user"
          git config user.email "actions@users.noreply.github.com"

          # remove gitlink & files
          git rm -r --cached ops || true
          rm -rf ops || true
          [ -f .gitmodules ] && rm -f .gitmodules || true

          git add -A
          if git diff --cached --quiet ; then
            echo "Nothing to remove."
            exit 0
          fi

          git commit -m "chore: remove broken 'ops' submodule pointer"

          # try direct push first
          set +e
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push origin "${{ github.event.inputs.branch }}"
          rc=$?
          set -e

          if [ $rc -ne 0 ]; then
            echo "Direct push blocked, falling back to PR..."
            FIX_BRANCH="nuke-ops-$(date +%s)"
            git checkout -b "$FIX_BRANCH"
            git push origin "$FIX_BRANCH"

            API="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls"
            TITLE="Remove broken 'ops' submodule pointer"
            BODY="This PR removes the stale submodule gitlink and .gitmodules to fix Pages builds."

            curl -sS -X POST "$API" \
              -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              -H "Accept: application/vnd.github+json" \
              -d "{\"title\":\"${TITLE}\",\"body\":\"${BODY}\",\"head\":\"${FIX_BRANCH}\",\"base\":\"${{ github.event.inputs.branch }}\"}"
          fi
