name: Sync private content to public

on:
  workflow_dispatch:
    inputs:
      ops_ref:
        description: "Private repo branch/tag to sync"
        required: false
        default: "main"
  schedule:
    - cron: "0 * * * *"   # 每小时同步一次，可按需调整

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PUBLIC repo (this repo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 仅需一个密钥：OPS_TOKEN（Fine-grained PAT，授予私库 Contents: Read）
      - name: Checkout PRIVATE content repo
        uses: actions/checkout@v4
        with:
          repository: enxpower/content-ops      # ← 换成你的私库全名：owner/repo
          token: ${{ secrets.OPS_TOKEN }}
          ref: ${{ github.event.inputs.ops_ref || 'main' }}
          path: ops

      - name: Inspect private repo (debug)
        run: |
          set -eux
          echo "Private repo root listing:"
          ls -la ops
          echo "Expect to see ads/, downloads/, static/data/ under ops/"

      - name: Sync whitelisted paths (ads, downloads, static/data)
        run: |
          set -eux
          # 确保目标目录存在
          mkdir -p ads downloads static/data

          # 只同步白名单；目标里多余文件用 --delete 清理
          # 注意：ads.json 位于 私库 ops/static/data/ads.json
          rsync -av --delete \
            --include='static/data/ads.json' \
            --include='ads/***' \
            --include='downloads/***' \
            --exclude='*' \
            ops/ ./                   # ← 关键：源路径改为 ops/（不是 ops/content-ops/）

      - name: Commit & push if changed
        run: |
          set -eux
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git config user.name "actions-user"
            git config user.email "actions@users.noreply.github.com"
            git commit -m "chore: sync private content"
            git push
          fi
