name: Sync private content to public

on:
  schedule:
    - cron: "17 * * * *"   # 每小时第17分钟执行（避开整点流量）
  workflow_dispatch: {}     # 允许手动运行

# 只需要向“当前公库”写内容
permissions:
  contents: write

concurrency:
  group: sync-content
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 不使用默认GITHUB_TOKEN，避免多余权限

      # 使用 GitHub App 生成只读安装令牌（更安全）
      - name: Generate installation token (read-only)
        id: app_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          installation_id: ${{ secrets.APP_INSTALLATION_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout private content repo (read-only)
        uses: actions/checkout@v4
        with:
          repository: enxpower/content-ops   # ← 改成你的私库路径（org/repo）
          ref: main                          # 或者 content 分支名
          token: ${{ steps.app_token.outputs.token }}
          path: _content

      - name: Sync selected content into public repo
        shell: bash
        run: |
          set -euo pipefail

          # 目标目录（不存在则创建）
          mkdir -p static/data ads downloads

          # 1) JSON 配置 → /static/data/
          if [ -d _content/json ]; then
            rsync -av --delete _content/json/ static/data/
          fi

          # 2) 广告/横幅素材 → /ads/
          if [ -d _content/ads ]; then
            rsync -av --delete _content/ads/ ads/
          fi

          # 3) 下载文件（PDF/ZIP等） → /downloads/
          if [ -d _content/downloads ]; then
            rsync -av --delete _content/downloads/ downloads/
          fi

      - name: Commit & push if changes
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"

          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: sync private content"
            git push
          fi
