name: Sync private content to public

on:
  workflow_dispatch:
    inputs:
      ops_ref:
        description: "Private repo branch/tag to sync"
        required: false
        default: "main"
  schedule:
    - cron: "0 * * * *"   # 每小时同步一次，可按需调整

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PUBLIC repo (this repo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout PRIVATE content repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.OPS_REPO }}     # 形如 org/private-content
          token: ${{ secrets.OPS_TOKEN }}         # PAT 或 repo token
          ref: ${{ github.event.inputs.ops_ref || 'main' }}
          path: ops

      # ✅ 关键：移除历史残留的子模块指针（gitlink），就不会再触发 Pages 报错
      - name: Remove stray submodule pointer 'ops' (safe)
        run: |
          set -eux
          git rm -r --cached ops || true
          rm -rf ops || true
          test -f .gitmodules && git rm -f .gitmodules || true

      - name: Sync whitelisted paths (ads, downloads, static/data)
        run: |
          set -eux
          mkdir -p ads downloads static/data
          rsync -av --delete \
            --include='static/data/ads.json' \
            --include='ads/***' \
            --include='downloads/***' \
            --exclude='*' \
            ops/content-ops/ ./

      - name: Commit & push if changed
        run: |
          set -eux
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git config user.name "actions-user"
            git config user.email "actions@users.noreply.github.com"
            git commit -m "chore: sync private content & remove ops gitlink"
            git push
          fi
