name: Sync private content to public (dev-ui)

on:
  workflow_dispatch:
    inputs:
      content_ref:
        description: "Branch/Tag of PRIVATE repo (default: main)"
        required: false
        default: main
      dry_run:
        description: "Dry run (no commit/push)"
        type: boolean
        default: false
  schedule:
    - cron: "0 * * * *"  # hourly

permissions:
  contents: write

concurrency:
  group: sync-content-dev-ui
  cancel-in-progress: false

env:
  PUBLIC_BRANCH: dev-ui
  PRIVATE_REPO: ${{ secrets.PRIVATE_CONTENT_REPO }}   # e.g. owner/content-ops
  PRIVATE_TOKEN: ${{ secrets.PRIVATE_CONTENT_TOKEN }} # repo read token for private repo

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PUBLIC repo (dev-ui)
        uses: actions/checkout@v4
        with:
          ref: ${{ env.PUBLIC_BRANCH }}
          fetch-depth: 0

      - name: Show current branch
        run: |
          set -eux
          git rev-parse --abbrev-ref HEAD
          git status

      - name: Checkout PRIVATE repo (content ops)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.PRIVATE_REPO }}
          ref: ${{ github.event.inputs.content_ref || 'main' }}
          token: ${{ env.PRIVATE_TOKEN }}
          path: _ops_src
          fetch-depth: 1

      - name: Prepare target dirs
        run: |
          set -eux
          mkdir -p static/data ads downloads

      # ✅ 白名单复制：只允许这三类
      - name: Copy whitelisted content from PRIVATE -> PUBLIC
        run: |
          set -eux
          rsync -av --delete "_ops_src/static/data/ads.json" "static/data/ads.json"
          rsync -av --delete "_ops_src/ads/" "ads/"
          rsync -av --delete "_ops_src/downloads/" "downloads/" || true

      # ✅ 同步后做硬核校验：ads.json 必须完全一致
      - name: Verify ads.json is EXACTLY identical (private vs public)
        run: |
          set -eux
          cmp -s "_ops_src/static/data/ads.json" "static/data/ads.json" || (echo "ads.json mismatch after copy!" && exit 1)

      - name: Show diff summary
        run: |
          set -eux
          git status --porcelain || true
          git diff --stat || true

      - name: Commit & push if changed
        if: ${{ github.event.inputs.dry_run != 'true' }}
        run: |
          set -eux
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git config user.name  "actions-user"
            git config user.email "actions@users.noreply.github.com"
            git commit -m "chore: sync content from private repo → dev-ui"
            git push origin HEAD:${PUBLIC_BRANCH}
          fi
