name: Sync private content to public

on:
  schedule:
    - cron: "17 * * * *"   # hourly at :17 (UTC)
  workflow_dispatch: {}     # allow manual run

permissions:
  contents: write

concurrency:
  group: sync-content
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4

      # Create short-lived installation token for the private repo (no installation ID needed)
      - name: Create installation token (read-only)
        id: app_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: enxpower                  # your org/user
          repositories: content-ops        # your private content repo

      - name: Checkout private content repo (read-only)
        uses: actions/checkout@v4
        with:
          repository: enxpower/content-ops
          ref: main
          token: ${{ steps.app_token.outputs.token }}
          path: _content

      - name: Sync selected content into public repo
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p static/data ads downloads
          if [ -d _content/json ]; then rsync -av --delete _content/json/ static/data/; fi
          if [ -d _content/ads ]; then rsync -av --delete _content/ads/ ads/; fi
          if [ -d _content/downloads ]; then rsync -av --delete _content/downloads/ downloads/; fi

      # Remove the temp checkout so Pages won't see a nested repo
      - name: Cleanup temp checkout
        run: rm -rf _content

      - name: Commit & push if changes
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
          # Only stage the three target paths (avoid accidental submodule artifacts)
          git add -A static/data ads downloads
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: sync private content"
            git push
          fi
