name: Auto Update Feeds

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # ✅ 显式设置为环境变量

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install openai feedparser newspaper3k lxml_html_clean
          python -m nltk.downloader punkt

      - name: Run aggregator script
        run: |
          python scripts/aggregator.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add posts/
          git commit -m "Update feed content" || echo "No changes"
          git push
