name: Auto Update Feeds

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install openai feedparser
      - name: Run aggregator
        run: OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} python aggregator.py
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m 'Auto update feed content' || echo "No changes to commit"
          git push
